package com.tickethandling.constants;

public final class Queries {

	public static final String PIE_CHART_COUNT_QUERY = "SELECT  "
			+ "COUNT(CASE WHEN tm.`status`= 0 THEN 1 END)  AS openticketcount, "
			+ "COUNT(CASE WHEN tm.`status`= 1 THEN 1 END)  AS progressticketcount, "
			+ "COUNT(CASE WHEN tm.`status`= 2 THEN 1 END)  AS closedtcketcount, " + "COUNT(*) AS totalticketscount "
			+ "FROM ticketmetadata tm " + "WHERE tm.orgid = :orgid AND tm.depid = :depid "
			+ "GROUP BY tm.orgid,tm.depid ";

	public static final String TICKET_META_INFO_QUERY = "SELECT a.*   " + "FROM (   " + "SELECT   "
			+ "( SELECT ud.username FROM userdetails ud WHERE ud.userid = t.currentassigneeuserid ) as currentassignee, "
			+ "( select rolename from roletbl r where r.id in ( SELECT ud.username FROM userdetails ud WHERE ud.userid = t.currentassigneeuserid  ) ) as currentassigneerole,"
			+ " " + "tm.ticketid,   " + "t.title,   "
			+ "t.content, CASE WHEN b.userid IS NULL THEN 0 ELSE 1 END AS isBookMarked,   " + "(   "
			+ "SELECT ud.username   " + "FROM userdetails ud   "
			+ "WHERE ud.userid = tm.creatoruserid) AS createdUser,   " + "(   " + "SELECT ud.avatarid   "
			+ "FROM userdetails ud   " + "WHERE ud.userid = tm.creatoruserid) AS createdUseravatar,   "
			+ "tm.createdat,   " + "tm.tags,   " + "1 AS isViewable,   " + "   " + "   "
			+ "(CASE WHEN tm.`status` = 0 THEN 1 WHEN tm.`status` = 2 THEN 0 WHEN tm.`status` = 1 THEN (CASE WHEN EXISTS (   "
			+ "SELECT *   " + "FROM userdetails ud   " + "WHERE ud.userid = :userid AND ud.roleid = (   "
			+ "SELECT id   " + "FROM roletbl r   "
			+ "WHERE r.rolename='Manager')) THEN 1 WHEN t.currentassigneeuserid = :userid THEN 1 ELSE   "
			+ " 	0 END    " + "    " + ") ELSE    " + "0 END    " + "    " + ") AS isEditable,   "
			+ "t.updatedon,   " + "(   " + "SELECT ud.username   " + "FROM userdetails ud   "
			+ "WHERE ud.userid = t.closedbyuserid   " + ") AS closedby,   " + "   " + "(   " + "SELECT ud.avatarid   "
			+ "FROM userdetails ud   " + "WHERE ud.userid = t.closedbyuserid   " + ") AS closedbyavatar,   " + "   "
			+ "(   " + "SELECT rolename   " + "FROM roletbl   " + "WHERE id = (   " + "SELECT ud.roleid   "
			+ "FROM userdetails ud   " + "WHERE ud.userid = t.closedbyuserid)   " + ") AS closedbyrole   " + "FROM    "
			+ "ticket t   "
			+ "INNER JOIN ticketmetadata tm ON t.ticketid = tm.ticketid AND t.activestage = 1 AND tm.`status` = :ticketstatus and tm.depid = :depid and tm.orgid = :orgid   "
			+ "INNER JOIN userorgmap uo ON uo.orgid = :orgid AND uo.depid= :depid AND uo.userid = :userid   "
			+ "LEFT JOIN bookmarks b ON b.ticketid = tm.ticketid AND b.userid = :userid   " + "   " + ") a   "
			+ "WHERE    "
			+ " (a.isBookMarked = :isBookMarkedStatus1 OR a.isBookMarked = :isBookMarkedStatus2) and  ( a.content LIKE CONCAT('%',:contentFilter,'%') OR a.title LIKE CONCAT('%',:contentFilter,'%') ) "
			+ "ORDER BY a.createdat DESC   ";

	public static final String TICKET_META_INFO_QUERY_COUNT = "SELECT COUNT(*)   " + "FROM (   " + "SELECT "
			+ "( SELECT ud.username FROM userdetails ud WHERE ud.userid = t.currentassigneeuserid ) as currentassignee,"
			+ "( select rolename from roletbl r where r.id in ( SELECT ud.username FROM userdetails ud WHERE ud.userid = t.currentassigneeuserid ) ) as currentassigneerole,"
			+ "   " + "tm.ticketid,   " + "t.title,   "
			+ "t.content, CASE WHEN b.userid IS NULL THEN 0 ELSE 1 END AS isBookMarked,   " + "(   "
			+ "SELECT ud.username   " + "FROM userdetails ud   "
			+ "WHERE ud.userid = tm.creatoruserid) AS createdUser,   " + "(   " + "SELECT ud.avatarid   "
			+ "FROM userdetails ud   " + "WHERE ud.userid = tm.creatoruserid) AS createdUseravatar,   "
			+ "tm.createdat,   " + "tm.tags,   " + "1 AS isViewable,   " + "   " + "   "
			+ "(CASE WHEN tm.`status` = 0 THEN 1 WHEN tm.`status` = 2 THEN 0 WHEN tm.`status` = 1 THEN (CASE WHEN EXISTS (   "
			+ "SELECT *   " + "FROM userdetails ud   " + "WHERE ud.userid = :userid AND ud.roleid = (   "
			+ "SELECT id   " + "FROM roletbl r   "
			+ "WHERE r.rolename='Manager')) THEN 1 WHEN t.currentassigneeuserid = :userid THEN 1 ELSE   "
			+ " 	0 END    " + "    " + ") ELSE    " + "0 END    " + "    " + ") AS isEditable,   "
			+ "t.updatedon,   " + "(   " + "SELECT ud.username   " + "FROM userdetails ud   "
			+ "WHERE ud.userid = t.closedbyuserid   " + ") AS closedby,   " + "   " + "(   " + "SELECT ud.avatarid   "
			+ "FROM userdetails ud   " + "WHERE ud.userid = t.closedbyuserid   " + ") AS closedbyavatar,   " + "   "
			+ "(   " + "SELECT rolename   " + "FROM roletbl   " + "WHERE id = (   " + "SELECT ud.roleid   "
			+ "FROM userdetails ud   " + "WHERE ud.userid = t.closedbyuserid)   " + ") AS closedbyrole   " + "FROM    "
			+ "ticket t   "
			+ "INNER JOIN ticketmetadata tm ON t.ticketid = tm.ticketid AND t.activestage = 1 AND tm.`status` = :ticketstatus and tm.depid = :depid and tm.orgid = :orgid    "
			+ "INNER JOIN userorgmap uo ON uo.orgid = :orgid AND :depid= tm.depid AND uo.userid = :userid   "
			+ "LEFT JOIN bookmarks b ON b.ticketid = tm.ticketid AND b.userid = :userid   " + "   " + ") a   "
			+ "WHERE    "
			+ " (a.isBookMarked = :isBookMarkedStatus1 OR a.isBookMarked = :isBookMarkedStatus2) and  ( a.content LIKE CONCAT('%',:contentFilter,'%') OR a.title LIKE CONCAT('%',:contentFilter,'%') ) "
			+ "  GROUP BY a.ticketid ORDER BY a.createdat DESC ";
}
